### ISSUE TITLE
Setup for other datasets

### ISSUE THREAD

**Issue by ancientbees** [short-circuitt/LWPR#1]
First off, thanks for making this code available, it's really helpful for extending the comparison to other systems.

I wanted to check if you could also provide the code for assessing against the other datasets used in the paper. Particularly the SFU dataset, where you did some cropping/subsampling of the images?

Thanks in advance.

**Comment by short-circuitt** [comment]
Hi, I've added some files in the folder SFU Code to give an example. The only real difference is the "offsetimage" call when you load the image. I haven't actually tested this code with the framework here, so if there are errors let me know and I can fix them.

**Comment by ancientbees** [comment]
That's great, thanks for the swift reply! I'll let you know if I have any problems with it.
